- .pre-commit-config.yaml
- README.md
- api/models/__init__.py
- api/models/age_ranges.py
- api/models/days_time_slots.py
- api/models/enrollment_tests.py
- api/models/groups.py
- api/models/languages_levels.py
- api/models/log_events.py
- api/models/people.py
- django_webapps/settings_sample.py
- manage.py
- poetry.lock
- pyproject.toml
I also made sure `pyproject.toml` is compatible with #13
> Install `mypy`, add pre-commit hook, fix issues detected by `mypy` (including several methods in models)

- api/migrations/0002_data_migration.py
- api/migrations/data_migration_sources/enrollment_test_en.yaml
- api/migrations/data_migration_sources/enrollment_tests.yaml
> populate enrollment test

- api/models/people.py
> fix(`PersonalInfo`): Capitalize `first_name` and `last_name`, lowercase `email`

- api/migrations/0003_fake_data.py
> suppress `DatabaseError` correctly when generating fake data

- api/migrations/0002_data_migration.py
- api/models/constants.py
- api/models/enrollment_tests.py
- api/serializers/enrollment_test.py
- api/serializers/personal_info.py
- api/views/enrollment_test.py
- tests/baker_recipes.py
- tests/tests_api/test_enrollment_test.py
> Return result of enrollment test (level) without writing the answers to database

- api/admin.py
- api/models/people.py
- api/serializers/personal_info.py
- api/utils.py
> fix: prevent error screen for `PersonalInfo`, implement case-insensitive existence check in serializer

- api/exceptions.py
- api/serializers/errors.py
- api/serializers/personal_info.py
- api/views/personal_info.py
- tests/tests_api/test_personal_info.py
> Use 409 instead of 400 in personal_info/check_existence/

- tests/conftest.py
- tests/tests_api/test_enrollment_test.py
- tests/tests_api/test_group.py
- tests/tests_api/test_personal_info.py
- tests/tests_api/test_student.py
- tests/tests_api/test_teacher.py
- tests/tests_api/test_teacher_under_18.py
fix all bake.make with models that contain unique constraints
> fix tests generated values

- api/processors/actions/group/abort.py
- api/processors/actions/group/confirm_ready_to_start.py
- api/processors/actions/group/create.py
- api/processors/actions/group/start.py
- api/processors/auxil/log_event_creator.py
- api/processors/group.py
- api/views/group.py
- tests/tests_api/test_group.py
> API view: Confirm that `Group` is ready to start

- api/admin.py
> #192: Fix model validation

- api/filters/student.py
- api/filters/teacher.py
> #219: Filter teachers and students by project status

- api/processors/actions/__init__.py
- api/processors/actions/student/missed_class.py
- api/processors/student.py
- api/serializers/__init__.py
- api/serializers/student/dashboard.py
- api/views/student.py
- tests/tests_api/test_student.py
> Student missed class view

- api/models/choices/log_event_type.py
- api/processors/actions/__init__.py
- api/processors/actions/student/went_on_leave.py
- api/processors/actions/teacher/went_on_leave.py
- api/processors/student.py
- api/processors/teacher.py
- api/views/student.py
- api/views/teacher.py
- tests/tests_api/test_student.py
- tests/tests_api/test_teacher.py
> Add went on leave view  for teacher and student

- api/serializers/__init__.py
- api/serializers/coordinator.py
- api/urls.py
- api/views/__init__.py
- api/views/coordinator.py
- tests/tests_api/test_coordinator.py
> Add coordinator view set

- api/processors/actions/__init__.py
- api/processors/actions/student/offer_join_group.py
- api/processors/student.py
- api/serializers/__init__.py
- api/serializers/student/dashboard.py
- api/views/student.py
- tests/tests_api/test_student.py
> Add offer join group view

- api/processors/actions/__init__.py
- api/processors/actions/student/expelled.py
- api/processors/actions/teacher/expelled.py
- api/processors/student.py
- api/processors/teacher.py
- api/views/student.py
- api/views/teacher.py
- tests/tests_api/test_student.py
- tests/tests_api/test_teacher.py
> Add expelled view for teacher and student

- api/processors/actions/__init__.py
- api/processors/actions/student/completed_oral_interview.py
- api/processors/actions/student/finished_oral_interview.py
- api/processors/student.py
- api/serializers/__init__.py
- api/serializers/shared.py
- api/serializers/student/dashboard.py
- api/views/student.py
- api/views/teacher.py
- tests/tests_api/test_student.py
- tests/tests_api/test_teacher.py
> Add view to confirm that student finished oral interview

- api/processors/actions/group/__init__.py
- api/processors/actions/student/transfer.py
- api/processors/actions/teacher/transfer.py
- api/processors/services/group_builder.py
- tests/tests_api/test_student.py
- tests/tests_api/test_teacher.py
> Remove redundant save() calls

- api/processors/__init__.py
- api/processors/actions/__init__.py
- api/processors/actions/coordinator/__init__.py
- api/processors/actions/coordinator/create.py
- api/processors/actions/student/create.py
- api/processors/actions/teacher/create.py
- api/processors/coordinator.py
- api/processors/student.py
- api/processors/teacher.py
- api/serializers/student/internal.py
- api/serializers/teacher/internal.py
- api/views/coordinator.py
- api/views/student.py
- api/views/teacher.py
- tests/tests_api/test_coordinator.py
- tests/tests_api/test_student.py
- tests/tests_api/test_teacher.py
> Add log events on person creation

- api/processors/actions/__init__.py
- api/processors/actions/teacher/finished_but_stays_in_project.py
- api/processors/teacher.py
- api/views/teacher.py
- tests/tests_api/test_teacher.py
> Add teacher finished studies and stays in project view

- api/serializers/group/minified.py
Closes #352 
Tiny PR to bring the API in line with the figma mockups
> Add group schedule to the `groups` field in `teacher_with_personal_info` view

- django_webapps/scripts/db_population/base_populator.py
- django_webapps/scripts/db_population/parsers/common_parsers.py
- django_webapps/scripts/db_population/parsers/teacher_parsers.py
- django_webapps/scripts/db_population/populate_coordinators.py
- django_webapps/scripts/db_population/populate_teachers.py
- django_webapps/scripts/db_population/utils.py
> feat: add coordinator populator, add base populator

- api/views/personal_info.py
- django_webapps/scripts/db_population/README
- django_webapps/scripts/db_population/populate_all.sh
- django_webapps/scripts/db_population/populate_teachers.py
> Add create or get personal info for teacher, add readme for scripts

- django_webapps/scripts/db_population/parsers/common_parsers.py
Sometimes geocoder is unavailable for some reason, some strings are not valid for him, apparently
> fix: add handler for GeocoderUnavailable error

- api/admin/group.py
> feat: add line breakers at different columns names

- api/admin/coordinator.py
- api/models/personal_info.py
- django_webapps/settings_sample.py
- templates/admin/actions.html
Closes #413
>[!IMPORTANT] 
> `settings.py` will need to be updated on server after merging
> Override action template and group name in coordinator page

- api/admin/coordinator.py
> Coordinators' table: add sorting by other columns (make cells in header row clickable)

- api/views/personal_info.py
- uv.lock
bot awaits some json data and when there is None we're getting an error
> fix: personal info check now returns also json data
